# Node.js Function App to Linux on Azure
# Build a Node.js function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '2a05444f-fda5-4d00-88c1-3b4ecffd4178'

  # Function app dev
  functionAppName: 'azure-starter-functions'
 
  # Environment dev
  environmentName: 'azure-starter-functions'
 
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        cd functions
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'Build azure functions'
    
    - script: |
        cd website
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'Build static site'
      
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: 'functions'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
    
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:            
          - task: AzureFunctionApp@1
            displayName: 'Azure Functions App Deploy: azure-starter-functions'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
          - task: AzureCLI@2
            displayName: 'Azure CLI Deploy: azure-static-site'
            inputs:
              azureSubscription: 'Pay-As-You-Go (a95ff90c-9450-4f17-ac8f-f30c08a0666f)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob upload-batch -s website/dist -d $STATIC-SITE-TARGET --account-name $ACCOUNT-NAME --account-key $AZURE-STORAGE-ACCESS-KEY'
              addSpnToEnvironment: true
              failOnStandardError: true
